**Icha Meisya Kurnia (25031554047)**

**Putri Najwa Zuleyka Al Hasni (25031554076)**

In [23]:
import numpy as np
import pandas as pd
import requests
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import sklearn
import nltk
nltk.download('stopwords')
from IPython.display import display, HTML

url = "https://api.spaceflightnewsapi.net/v4/articles/?limit=100"
response = requests.get(url)
data_json = response.json()

data = pd.DataFrame(data_json['results'])
data['summaries'] = data['summary']
data['titles'] = data['title']

print("Total rows : ", len(data))
display(HTML(data.head().to_html()))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Total rows :  100

In [10]:
import pandas as pd
from IPython.display import HTML, display
from sklearn.metrics.pairwise import cosine_similarity

TopK = 10
query = "moon space station launch mission"
documents_tfidf_features = vectorizer.transform(corpus)
query_tfidf_features = vectorizer.transform([query])

similarities = cosine_similarity(documents_tfidf_features, query_tfidf_features)
top_indices = similarities[:, 0].argsort()[::-1][:TopK]

titles = []
abstracts = []

for doc_index in top_indices:
    titles.append(data.iloc[doc_index]["title"])
    abstracts.append(data.iloc[doc_index]["summary"].replace("\n", " "))

results = pd.DataFrame(
    {
        "Title": titles,
        "Abstract/Summary": abstracts,
        "Similarities": similarities[top_indices, 0],
    }
)

display(HTML(results.to_html()))

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

stemmer = PorterStemmer()
stop_words = set(stopwords.words("english"))
corpus = []

for summary in data.summaries.to_list():
    tokens = summary.lower().split()
    tokens = [stemmer.stem(token) for token in tokens if token not in stop_words]
    corpus.append(" ".join(tokens))

print(corpus[0])

vectorizer = TfidfVectorizer(sublinear_tf=True, max_features=5000)
vectorizer.fit_transform(corpus)

print("Total features ", vectorizer.get_feature_names_out().shape)
vectorizer.get_feature_names_out()[:1000]

apod scienc apod apod: 2026 octob 9… today’ apod archiv submiss index search calendar rss educ discuss apod astronomi pictur day discov cosmos! day differ imag photograph fascin univers featured, along brief explan written profession astronomer. stickney crater explanation: stickney […]
Total features  (234,)

array(['12', '13', '15', '19', '20', '2007', '2026', '237', '30',
       'aboard', 'acceler', 'across', 'adenot', 'aerospac', 'affect',
       'again', 'age', 'agenc', 'agency', 'along', 'america', 'andrey',
       'angeles', 'announc', 'apod', 'archiv', 'arriv', 'astronaut',
       'astronom', 'astronomer', 'astronomi', 'astrophys', 'atmospher',
       'base', 'blur', 'brief', 'bring', 'brown', 'burst', 'calendar',
       'california', 'capabl', 'caus', 'celesti', 'center', 'chemic',
       'close', 'cloudi', 'coast', 'confer', 'conjunct', 'contribut',
       'cosmonaut', 'cosmos', 'could', 'country', 'crater', 'crew',
       'dark', 'date', 'day', 'debris', 'deepen', 'demonstr', 'differ',
       'discov', 'discuss', 'distant', 'dragon', 'dwarfs', 'edt', 'educ',
       'emiss', 'end', 'enigmatic', 'epoch', 'esa', 'european',
       'exoplanets', 'explan', 'explanation', 'explor', 'explorer',
       'fascin', 'fast', 'featured', 'fedyaev', 'find', 'first', 'flash',
       'flood', 'forc', 'four', 'frb', 'freedom', 'futur', 'galaxi',
       'get', 'giant', 'golden', 'hathaway', 'heavi', 'histori', 'host',
       'hous', 'houston', 'ice', 'imag', 'in', 'index', 'initi', 'innov',
       'inspect', 'intern', 'invit', 'jack', 'jame', 'japan', 'jaxa',
       'jessica', 'johnson', 'join', 'journal', 'jst', 'launch',
       'leaders', 'light', 'line', 'lo', 'long', 'longer', 'martian',
       'media', 'meir', 'member', 'mid', 'million', 'millisecond',
       'mission', 'mmx', 'moment', 'monday', 'month', 'moon', 'morning',
       'nasa', 'never', 'new', 'news', 'object', 'ocean', 'oct', 'octob',
       'offic', 'orbit', 'origin', 'ostp', 'pacif', 'particularli',
       'peopl', 'photograph', 'photomet', 'pictur', 'pinpoint', 'policy',
       'preview', 'profession', 'program', 'propuls', 'publish', 'radio',
       'rain', 'reduc', 'reionization', 'remain', 'repair', 'replac',
       'rich', 'roscosmo', 'rss', 'safe', 'satellit', 'schedul', 'scienc',
       'scientif', 'search', 'seen', 'septemb', 'service', 'seven',
       'shape', 'shed', 'show', 'sinc', 'small', 'sophi', 'spac', 'space',
       'spacecraft', 'spacex', 'spectro', 'spent', 'spherex', 'splash',
       'sspicy', 'star', 'station', 'stickney', 'submiss', 'summit',
       'support', 'tanegashima', 'technolog', 'teleconfer', 'telescop',
       'thursday', 'today', 'top', 'tuesday', 'two', 'uncertain',
       'understand', 'univers', 'universe', 'unlik', 'use', 'vandenberg',
       'washington', 'webb', 'week', 'white', 'widespread', 'world',
       'written'], dtype=object)

In [13]:
import pandas as pd
from IPython.display import HTML, display
from scipy.spatial.distance import cdist
from sklearn.feature_extraction.text import CountVectorizer

TopK = 10
query = "moon space station launch mission"
vectorizer_bin = CountVectorizer(binary=True, max_features=5000)
documents_binarized_features = vectorizer_bin.fit_transform(corpus).toarray()
query_binarized_features = vectorizer_bin.transform([query]).toarray()

similarities = 1 - cdist(
    documents_binarized_features, query_binarized_features, metric="jaccard"
)
top_indices = similarities[:, 0].argsort()[::-1][:TopK]

titles = []
abstracts = []
similarity_scores = []

for doc_index in top_indices:
    titles.append(data.iloc[doc_index]["title"])
    abstracts.append(data.iloc[doc_index]["summary"].replace("\n", " "))
    similarity_scores.append(similarities[doc_index, 0])

results = pd.DataFrame(
    {
        "Title": titles,
        "Abstract/Summary": abstracts,
        "Similarities": similarity_scores,
    }
)

display(HTML(results.to_html()))

Berdasarkan kode tersebut, metode TF-IDF dan Cosine Simularity dapat mengurutkan artikel paling spesifik secara kontekstual dengan memberikan skor tinggi pada artikel "NASA's SpaceX Crew-12 Splashes Down..." karena mampu dalam memberikan bobot yang lebih pada kata kunci seperti space station dan mission. Sementara metode Binary Count dan Jaccard Similarity mengurutkan artikel "NASA Briefing to Highlight Contributions to Martian Moons Mission"  di urutan pertama, karena pengukurannya berdasarkan pada persentase jumlah irisan kata unik antar Query dan dokumen.

Kedua metode ini efektif dalam memilah data karena secara tepat memberikan skor 0,00 pada artikel yang tidak relevan sama sekali seperti berita banjir Thailand.